export const MAX_NUM_NAME_TOKENS = 20;
export const NUM_NAME_PLACHOLDERS = 4;
export const NUM_RECIPE_SUGGESTIONS = 6;
export const NUM_RECIPE_SUBSTITUTIONS = 6;
export const NUM_RECIPE_EQUIPMENT_ADAPTATIONS = 4;
export const NUM_DIETARY_ALTERNATIVES = 6;
export const MAX_NUM_DESCRIPTION_TOKENS = 40;
export const NUM_DESCRIPTION_PLACHOLDERS = 12;
