export const MISC_ONBORADING_QUESTIONS = [
  { id: "microwave", question: "Do you own a microwave?" },
  { id: "oven", question: "Is an oven available?" },
  { id: "blender", question: "Do you have a blender?" },
  { id: "spicy_food", question: "Do you like spicy food?" },
  { id: "quick_recipes", question: "Prefer quick recipes (under 30 minutes)?" },
  { id: "outdoor_grilling", question: "Is outdoor grilling an option?" },
  { id: "cook_with_alcohol", question: "Do you cook with alcohol?" },
  { id: "prefer_vegetarian", question: "Do you prefer vegetarian meals?" },
  { id: "like_seafood", question: "Do you like seafood?" },
  { id: "slow_cooker", question: "Is a slow cooker available?" },
  { id: "organic_ingredients", question: "Do you prefer organic ingredients?" },
  { id: "cooking_for_kids", question: "Are you cooking for kids?" },
  { id: "seasonal_recipes", question: "Do you follow seasonal recipes?" },
  { id: "low_sodium", question: "Do you need low-sodium recipes?" },
  { id: "fresh_herbs", question: "Prefer using fresh herbs?" },
  { id: "baking", question: "Do you bake often?" },
  { id: "one_pot_meals", question: "Do you prefer one-pot meals?" },
  {
    id: "international_cuisine",
    question: "Do you enjoy international cuisine?",
  },
  { id: "gourmet_cooking", question: "Are you interested in gourmet cooking?" },
  { id: "dairy_substitutes", question: "Do you use dairy substitutes?" },
];

export const EQUIPMENT_ITEMS = [
  { id: "air_fryer", equipment: "Air Fryer" },
  { id: "slow_cooker", equipment: "Slow Cooker" },
  { id: "instant_pot", equipment: "Instant Pot" },
  { id: "wok", equipment: "Wok" },
  { id: "sous_vide", equipment: "Sous Vide" },
  { id: "blender", equipment: "Blender" },
  { id: "stand_mixer", equipment: "Stand Mixer" },
  { id: "food_processor", equipment: "Food Processor" },
  { id: "dutch_oven", equipment: "Dutch Oven" },
  { id: "cast_iron_skillet", equipment: "Cast Iron Skillet" },
  { id: "pressure_cooker", equipment: "Pressure Cooker" },
  { id: "juicer", equipment: "Juicer" },
  { id: "pasta_maker", equipment: "Pasta Maker" },
  { id: "bread_maker", equipment: "Bread Maker" },
  { id: "ice_cream_maker", equipment: "Ice Cream Maker" },
  { id: "electric_grill", equipment: "Electric Grill" },
  { id: "pizza_stone", equipment: "Pizza Stone" },
  { id: "coffee_grinder", equipment: "Coffee Grinder" },
  { id: "espresso_machine", equipment: "Espresso Machine" },
  { id: "toaster_oven", equipment: "Toaster Oven" },
];
