import {
  DietSettings,
  EquipmentSettings,
  ExperienceLevel,
  TasteSettings,
} from "@/types";
import { atom, map } from "nanostores";

export const $equipment = map<EquipmentSettings>({
  microwave: undefined,
  conventionalOven: undefined,
  toasterOven: undefined,
  airFryer: undefined,
  slowCooker: undefined,
  instantPot: undefined,
  pressureCooker: undefined,
  electricGrill: undefined,
  castIronSkillet: undefined,
  wok: undefined,
  dutchOven: undefined,
  blender: undefined,
  standMixer: undefined,
  pizzaStone: undefined,
  sousVide: undefined,
  foodProcessor: undefined,
  juicer: undefined,
  // riceCooker: undefined,
  pastaMaker: undefined,
  breadMaker: undefined,
  // waffleIron: undefined,
  iceCreamMaker: undefined,
  coffeeGrinder: undefined,
  espressoMachine: undefined,
});

export const $diet = map<DietSettings>({
  glutenFree: undefined,
  vegan: undefined,
  vegetarian: undefined,
  lactoseIntolerant: undefined,
  eggFree: undefined,
  nutFree: undefined,
  seafoodFree: undefined,
  wheatFree: undefined,
  soyFree: undefined,
  lowSodium: undefined,
  usesDairySubstitutes: undefined,
  noAlcohol: undefined,
  sugarFree: undefined,
  lowCarb: undefined,
  paleo: undefined,
  keto: undefined,
  mediterraneanDiet: undefined,
  pescatarian: undefined,
  flexitarian: undefined,
  whole30: undefined,
  diabeticFriendly: undefined,
  halal: undefined,
  kosher: undefined,
  ayurvedic: undefined,
});

export const $preferences = map<TasteSettings>({
  preferSaltyOverSweet: undefined,
  preferChocolateyOverFruity: undefined,
  enjoyRawOnions: undefined,
  needSpicyElements: undefined,
  preferBlackCoffee: undefined,
  likeLemonInBeverages: undefined,
  favorBoldCheeses: undefined,
  preferHeavilySeasoned: undefined,
  enjoyBitterFoods: undefined,
  preferRawVegetables: undefined,
  breadBetterWithButterOrOil: undefined,
  preferCreamyOverChunkySoups: undefined,
  chooseRiceOverPotatoes: undefined,
  preferScrambledOverFriedEggs: undefined,
  likeGrilledFishOverFried: undefined,
  preferFruitAsSnack: undefined,
  dessertBetterWarm: undefined,
  enjoyGingerInFood: undefined,
  saladAppealingWithoutDressing: undefined,
  preferPastaWithRedSauce: undefined,
});


export const $experienceLevel = atom<ExperienceLevel | undefined>(undefined);
