import { Card } from "@/components/display/card";
import MarkdownRenderer from "@/components/display/markdown";

export default async function Page() {
  return (
    <div className="max-w-3xl mx-auto w-full p-4">
      <Card className="p-4">
        <MarkdownRenderer markdownText={TERMS_MARKDOWN} />
      </Card>
    </div>
  );
}

const TERMS_MARKDOWN = `
### Introduction and Acceptance of Terms

Version Effective Date: 01-12-2024

Thank you for using KitchenCraft. These Terms of Service ("Agreement") detail your rights regarding the content you create or interact with on KitchenCraft, your usage of our services, and other important aspects such as dispute resolution. Please read this Agreement carefully. Our privacy policy, which outlines how we handle your data, can be found [here or insert link].

This Agreement is made between Open Game Collective, LLC and you, the individual or entity agreeing to these terms ("Customer", "You", or "Your"). It governs your access to and use of KitchenCraft.

This Agreement becomes effective when you are presented with it and proceed to use KitchenCraft (the "Effective Date"). We may update these terms periodically, and your continued use of KitchenCraft constitutes acceptance of any revised terms. If you do not agree to the terms of this Agreement, you should discontinue your use of KitchenCraft.

Please note that other documents, such as our Community Guidelines, may also govern your use of KitchenCraft and are incorporated by reference into this Agreement.

### 1. Service Availability and Quality

KitchenCraft, currently in its beta phase, is continually evolving. We strive to improve the Services, which include features like recipe generation, cooking tips, and other functionalities.

**Modifications and Changes**: The Services are subject to change, which may include updates to features, algorithms, and overall user experience. We cannot guarantee the Services' quality, stability, uptime, or reliability during the beta phase.

**"As Is" Provision**: KitchenCraft and all its features are provided "AS IS," without any warranties or conditions, either express or implied. This includes, but is not limited to, warranties of title, non-infringement, merchantability, or fitness for a particular purpose. You assume all risks associated with the use of our Services and are responsible for determining the appropriateness of using the generated content.

**Usage Restrictions**: You may not use KitchenCraft for developing or offering competitive products or services, reverse engineer our Services, use automated tools to interact with the Services, or resell/redistribute access. Usage of the Services must comply with intellectual property laws, and violating these may lead to legal action or a ban from the Service.

**Investigative Rights**: Open Game Collective, LLC reserves the right to investigate complaints or reported violations of these Terms and take appropriate action, including reporting suspected unlawful activities to relevant authorities.

### 2. Age Requirements

By accessing KitchenCraft, you confirm that you are at least 13 years old or meet the minimum age of digital consent in your country. If you are under the age of majority in your jurisdiction but old enough to legally access the Services, you must have your parent or guardian’s consent to these terms.

**Parental Responsibility**: If you are a parent or legal guardian and you allow your child to use KitchenCraft, you agree to these terms and are responsible for your child's activity on the Services.

**Content Suitability**: While we aim for KitchenCraft to be suitable for a general audience, we cannot guarantee that all content generated by our system will always align with this goal. Please exercise discretion when using the Services.

### 3. Your Information

In the course of using KitchenCraft, you may provide us with personal information such as your email address, username, preferences, and the content you create or interact with. Our handling of your personal data is described in our privacy policy, available [insert link or location here].

### 4. Content Rights

#### Your Rights
You own all content you create using KitchenCraft to the fullest extent possible under applicable law, subject to:

- Obligations imposed by this Agreement and third-party rights.
- If you enhance or modify others’ content, your modifications are yours, but the original content remains owned by its creator.

Consult a legal professional for specific intellectual property law guidance in your jurisdiction. Your ownership persists even if you cease using KitchenCraft.

#### Rights You Grant to Open Game Collective, LLC
By using KitchenCraft, you grant us a non-exclusive, worldwide, sublicensable, royalty-free license to:

- Reproduce, display, perform, distribute, and create derivative works from the content and prompts you input.
- This license is for operating, promoting, and improving KitchenCraft and developing new services, and it survives the termination of this Agreement.

#### Community Sharing and Remixing
KitchenCraft is an open community:

- Content and prompts you create or input are by default publicly viewable and may be used and remixed by others.
- Be aware that content created in shared or public spaces can be viewed and used by others in those spaces.

### 5. DMCA and Takedowns Policy

#### Notification Procedures
We respect intellectual property rights and take claims of infringement seriously. If you believe that material on KitchenCraft violates your copyright or trademark, please send a notice of claimed infringement to dmca@kitchencraft.ai with the following:

- Your physical or electronic signature.
- Identification of the infringed work and the material believed to be infringing.
- Your contact information (name, address, phone number, email).
- A statement of good faith belief that the use is not authorized.
- A statement that the information is accurate and, under penalty of perjury, you are authorized to act on behalf of the copyright owner.

#### Counter-Notification Procedures
If you believe material was wrongly removed, you can file a counter-notification to our designated agent. Include:

- Your signature and identification of the material removed.
- Your contact information.
- A statement under penalty of perjury that you believe the material was removed by mistake.
- Consent to the jurisdiction of your local federal court, and agreement to accept service from the person who provided the initial complaint.

Be aware that false claims can lead to liability for damages under DMCA.

### 6. Dispute Resolution and Governing Law

In the event of a dispute, controversy, or claim arising from or related to these Terms ("Dispute"), the parties will first attempt to resolve the Dispute amicably within 30 days. If unresolved, the Dispute shall be settled by binding arbitration, conducted by a neutral arbitration body in accordance with its rules. The arbitration will take place in [Specify Location], and the proceedings will be in English.

The arbitration award will be final and binding, and enforceable in any court of competent jurisdiction. Each party will bear its own legal fees and expenses. This arbitration agreement does not preclude parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.

### 7. Unlimited Service and Rate Limiting

During KitchenCraft's beta phase, usage will not be metered. However, we reserve the right to implement rate limiting measures to maintain service quality and to prevent disruptions to other users. We will make efforts to notify affected users in advance whenever possible.

### 8. Community Guidelines

Respect and kindness are cornerstones of the KitchenCraft community. We ask that you:

- Respect other members and staff.
- Avoid creating or sharing content that is disrespectful, aggressive, hateful, or abusive.
- Refrain from posting adult content or gore.
- Respect intellectual property rights and do not distribute others' creations without permission.
- Do not use KitchenCraft for illegal activities or to deceive or defraud.
- Be thoughtful about sharing content outside the KitchenCraft community.
- Violations of these guidelines may result in a ban from our services.

### 9. Limitation of Liability and Indemnity

KitchenCraft is provided "as is" without any guarantees. We will not be liable for any indirect, special, incidental, or consequential damages arising from your use of the service.

You are responsible for your use of KitchenCraft. If your actions cause harm or a dispute, you are solely responsible. Intentional infringement of intellectual property rights that incurs costs to us will result in our pursuit of compensation.

### 10. Miscellaneous

- **Force Majeure**: We are not liable for delays or failures caused by events beyond our reasonable control.
- **No Agency**: This Agreement does not create an agency, partnership, or joint venture.
- **Severability**: If any part of this Agreement is unenforceable, the rest remains in effect.
- **No Third-Party Beneficiaries**: This Agreement benefits only the parties to it.
- **Survival**: Obligations expected to survive the termination of this Agreement will do so.
- **Governing Law**: These Terms are governed by the laws of [Specify Jurisdiction], excluding conflict of law principles.
`;
